### PR TITLE
Experimental role Doppelganger and Blackmailer fix

### PR DESCRIPTION
**Pull request by ryuk201198**
Known issue :- If host steals identity as Doppelganger and wins the end win screen shows the last stolen name.
Needs more testing

### CODE REVIEW

**Comment by Tommy-XL** [comment]
Will camouflage be broken?  And it's even better not to use Camouflage.cs, you can just copy the code from there and make it separately in Doppelganger.cs
For example, how does the Devourer role do this

**Comment by ryuk201198** [comment]
Camouflage will not be broken. I made skin change function in Doppelganger.cs itself. I had to make changes in Camouflage.cs because :-
1. Doppelganger was resetting to OG skin after camouflage ended.
2. CheckGameEndPatch.cs used  Camouflage.cs to reset any camouflage

**Comment by ryuk201198** [comment]
latest commit might fix blackmailer spamming chat bug

**Comment by Loonie-Toons** [comment]
Well Blackmailer generally didn't work anyway.
Messages wouldn't save correctly, resulting in it only repeating the messages sent at the beginning of the meeting.

**Comment by ryuk201198** [comment]
The messages that were being saved was before the game had started... i made it so that it saves the messages when the game has started. You'd notice the change in ChatManager.cs changed from if (!GameState.IsInTask) to if (GameState.IsInTask)

**Pull request merged**
